### ISSUE TITLE
VB12Path_FunctionProfiler.PL line 169 error

### ISSUE THREAD

**Issue by rharbeitner** [qichao1984/VB12Path#2]
I am exploring VB12Path with a set of marine metagenomes. I am getting the warning at line 169 in VB12Path_FunctionProfiler.PL:  bin_23 was not found in /sample_directory/big_sampleinfo.txt, please check!

However, my sample (bin_23) is a line in my sampleinfo.txt file. When I look at the generated output files so far, there is a .diamond file generated for every .fasta file I have in my sampleinfo.txt file before the error killed the run. 

Operating System details:
[rharbeit@hb ~]$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

The command run:
perl VB12Path_FunctionProfiler_ed.PL -d /sample_directory/ -m diamond -f fasta -s nucl -si /sample_directory/big_sampleinfo.txt -o /sample_directory/VB12_big_functional_profile.txt

where VB12Path_FunctionProfiler_ed.PL is an updated script with my directory locations edited.

Contents of sampleinfo.txt file:
[rharbeit@hb VB12Path]$ cat /sample_directory/big_sampleinfo.txt
bin_1   24
bin_2   120
bin_3   22
bin_4   15
bin_5   7
bin_6   20
bin_7   13
bin_8   29
bin_9   9
bin_10  24
bin_11  17
bin_12  11
bin_13  23
bin_14  20
bin_15  5
bin_16  13
bin_17  7
bin_18  8
bin_19  6
bin_20  13
bin_21  17
bin_22  5
bin_23  6
bin_24  4
bin_25  3
bin_26  4
bin_27  2
bin_28  1

original fasta files and generated diamond files in sample_directory:
[rharbeit@hb sample_directory]$ ls -lh bi*
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  296 Jun  7 11:46 big_sampleinfo.txt
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.8K Jun  7 11:50 bin_10.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 4.0M May 14 13:18 bin_10.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.4K Jun  7 11:51 bin_11.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 3.8M May 14 13:18 bin_11.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  866 Jun  7 11:56 bin_12.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 3.8M May 14 13:18 bin_12.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.7K Jun  7 11:57 bin_13.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 3.6M May 14 13:18 bin_13.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.6K Jun  7 11:57 bin_14.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 3.2M May 14 13:18 bin_14.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  400 Jun  7 12:02 bin_15.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 3.2M May 14 13:18 bin_15.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.1K Jun  7 12:03 bin_16.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 3.1M May 14 13:18 bin_16.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  511 Jun  7 12:04 bin_17.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 3.0M May 14 13:19 bin_17.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  643 Jun  7 12:05 bin_18.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 2.9M May 14 13:19 bin_18.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  503 Jun  7 12:07 bin_19.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 2.9M May 14 13:19 bin_19.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.9K Jun  7 11:49 bin_1.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 5.0M May 14 13:18 bin_1.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.1K Jun  7 12:08 bin_20.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 2.9M May 14 13:19 bin_20.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.3K Jun  7 12:09 bin_21.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 2.8M May 14 13:19 bin_21.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  409 Jun  7 12:10 bin_22.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 2.3M May 14 13:19 bin_22.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  379 Jun  7 12:11 bin_23.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.5M May 14 13:19 bin_23.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  331 Jun  7 12:12 bin_24.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.3M May 14 13:19 bin_24.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  218 Jun  7 12:12 bin_25.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.1M May 14 13:19 bin_25.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  320 Jun  7 12:13 bin_26.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 900K May 14 13:19 bin_26.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  182 Jun  7 12:13 bin_27.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 654K May 14 13:19 bin_27.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr   71 Jun  7 12:13 bin_28.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 344K May 14 13:19 bin_28.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 7.6K Jun  7 12:07 bin_2.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 4.8M May 14 13:19 bin_2.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.6K Jun  7 12:14 bin_3.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 4.7M May 14 13:19 bin_3.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.2K Jun  7 12:15 bin_4.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 4.3M May 14 13:19 bin_4.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  559 Jun  7 12:19 bin_5.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 4.2M May 14 13:19 bin_5.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.4K Jun  7 12:21 bin_6.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 4.1M May 14 13:20 bin_6.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.1K Jun  7 12:22 bin_7.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 4.1M May 14 13:20 bin_7.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 1.9K Jun  7 12:23 bin_8.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 4.1M May 14 13:20 bin_8.fasta
-rw-r--r-- 1 rharbeit ucsc_p_all_usr  702 Jun  7 12:25 bin_9.diamond
-rw-r--r-- 1 rharbeit ucsc_p_all_usr 4.1M May 14 13:20 bin_9.fasta

Do you have a suggestion for why I am receiving this error?

**Comment by Jiayin-zhou** [comment]
Hi, I have two suggestions on this error
1. Please check if there are special symbol (e.g. space) after the sample name in the big_sampleinfo.txt, and check if the formate of the big_sampleinfo.txt file is correct (i.e. it was created under the windows and may not be recognized when put under linux).
2.  You can try to copy the contents of the big_sampleinfo.txt file  into a new file and run the new file.
I hope my suggestion is helpful to you.

**Comment by rharbeitner** [comment]
Thanks for your suggestions. I generated a new sampleinfo file via vi and the problem was solved.
